### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by jsjk01** [congwulong/alipay_autojs#10]
19:48:42.349/E: Error: out of region: region = [1073,200,1,2000], image.size = [720,1280] (file:///android_asset/modules/__images__.js#523)
Error: out of region: region = [1073,200,1,2000], image.size = [720,1280]
    at buildRegion (file:///android_asset/modules/__images__.js:523:0)
    at file:///android_asset/modules/__images__.js:395:0
    at getHasEnergyfriend (/storage/emulated/0/脚本/alipay_auto.js:185:0)
    at enterOthers (/storage/emulated/0/脚本/alipay_auto.js:201:0)
    at mainEntrence (/storage/emulated/0/脚本/alipay_auto.js:42:0)
    at /storage/emulated/0/脚本/alipay_auto.js:24:0
手机分辨率：720 * 1280

**Comment by congwulong** [comment]
你好，我手头没有720分辨率的设备，无法进行适配。所以。。暂时无法支持
